### PR TITLE
fix getting the correct credential after search

### PR DESCRIPTION
**Pull request by JakKowalCzyk**

### CODE REVIEW

**Comment by swcurran** [comment]
@esune - please take a look.

@JakKowalCzyk - thanks for the PR.

**Comment by esune** [comment]
@JakKowalCzyk can you please describe how to reproduce the issue that this is going to fix, and how to reproduce it? Thanks!

**Comment by JakKowalCzyk** [comment]
@esune Of course.
Firstly, we discovered that sometimes when we search a registered company on the Greenlight, we select one and than we want to generate the graph for it, here is what happens:
- The graph shows us that any credentials were not issued and we can register the company - which is not true because we were able to search it and pick it
- The graph looks fine and it is marked with green color but when we will click on a credential it will move us to the OrgBook but to completely different company
So what we have discovered is that when You select a company after search and want to generate the graph for it, the Greenlight takes ID of company searched Name ID. We think that this is not correct because when we checked it in the database it turned out that Name ID is not equal to credential/topic ID of given company. 
In case it matters to reproduce the case, we discovered it when we were using Greenlight configured to have only 2 bcgov modified agents - Business Relationship and Registered corporation, moreover the Business Relationship was depending on Registered corporation and it was the second step in our flow. Actually it looks like this is the reason why we experienced this problem, anyway we had to make the change in our fork to have Greenlight working properly, maybe it is not necessary to change it in official repo.

**Comment by esune** [comment]
Thank you @JakKowalCzyk! That makes sense, thank you for submitting the PR. I added a change to make the behaviour consistent when search results are found.

**Pull request merged**
